export const mockThreads = [
  {
    id: '1',
    title: 'Ano ba talaga nangyari sa EDSA kanina?',
    author: 'Anonymous_123',
    category: 'News & Current Events',
    replies: 45,
    likes: 128,
    timestamp: '2 hours ago',
  },
  {
    id: '2',
    title: 'Best jollibee combo para sa budget?',
    author: 'Foodie_456',
    category: 'Food & Drinks',
    replies: 89,
    likes: 234,
    timestamp: '4 hours ago',
  },
  {
    id: '3',
    title: 'Bakit ang mahal ng bilihin ngayon?',
    author: 'Concerned_789',
    category: 'Economy',
    replies: 156,
    likes: 445,
    timestamp: '6 hours ago',
  },
  {
    id: '4',
    title: 'May nakita ba kayong bagong K-drama?',
    author: 'DramaLover_012',
    category: 'Entertainment',
    replies: 67,
    likes: 189,
    timestamp: '8 hours ago',
  },
  {
    id: '5',
    title: 'Traffic sa Manila sobrang grabe',
    author: 'Commuter_345',
    category: 'Transportation',
    replies: 201,
    likes: 567,
    timestamp: '10 hours ago',
  },
];
export const mockComments = [
  {
    id: '1',
    threadId: '1',
    author: 'Witness_111',
    content: 'I was there! May aksidente daw, kaya natraffic lahat.',
    likes: 23,
    timestamp: '1 hour ago',
  },
  {
    id: '2',
    threadId: '1',
    author: 'Commuter_222',
    content: 'Grabe ang haba ng pila sa MRT dahil dito',
    likes: 15,
    timestamp: '1 hour ago',
  },
  {
    id: '3',
    threadId: '1',
    author: 'NewsJunkie_333',
    content: 'May nakita akong post sa Twitter about this. Apparently may truck na bumagsak.',
    likes: 45,
    timestamp: '50 mins ago',
  },
  {
    id: '4',
    threadId: '1',
    author: 'Anonymous_444',
    content: 'Sana okay lang lahat ng involved 🙏',
    likes: 67,
    timestamp: '45 mins ago',
  },
];